### PR TITLE
Update GoldenGateAssemblyMethod.py

### PR DESCRIPTION
**Pull request by jlerman44**
This was hardcoded to 4 bp, but I realized it should be ```self.overhang_size```

### CODE REVIEW

**Comment by jlerman44** [comment]
@Zulko @veghp - follow up to the previous release. I found 1 more spot where 4bp overhang was hard-coded. This should resolve that.

**Comment by jlerman44** [comment]
@alexsongrj - FYI

**Comment by veghp** [comment]
Thanks, I merged into `dev` and also migrated to [Travis com](https://travis-ci.com/github/Edinburgh-Genome-Foundry/DnaWeaver/builds/235276394) so it will run the CI properly now (Travis org is retired). PDF Reports adds a bit of an overhead to testing, but perhaps it's good to include anyways. The test fails on a certain `pango_context_set_round_glyph_positions`. Based on [this conversation](https://github.com/Kozea/WeasyPrint/issues/1384) there may not be an easy solution.

I'll try and address it together with another issue, but any comments are welcome.

**Comment by jlerman44** [comment]
@veghp - will the Debian stable (11, Bullseye) release with updated Pango solve the issue? It is referenced in the conversation you linked. I believe it comes out tomorrow. Building a lot of tools from source to try to solve the issue failed miserably in my hands.

**Comment by veghp** [comment]
Thanks -- I believe Travis uses Ubuntu. I specified a WeasyPrint version [as recommended in their documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#linux), in the PDF Reports dependency. It passes build now. I'll have a look at another issue, then I will make a release.

**Comment by jlerman44** [comment]
@veghp - awesome. We did a test in our wet lab, and this code definitely does a thing!

**Comment by jlerman44** [comment]
@veghp - any chance you can push this to master & pypi sometime soon?

**Comment by veghp** [comment]
Fixing the other issue got delayed so I released v0.3.7 here and on PyPI now. Thanks for the patience

**Pull request merged**
